services:
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ../..:/workspaces:cached # Re-enable workspace mounting

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Explicit dependencies and networking
    depends_on:
      - db
    env_file:
      - .env.development.local

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    build:
      context: .
      dockerfile: database.Dockerfile
    volumes:
      - mongodb-data:/data/db
    env_file:
      - .env.development.local
    restart: unless-stopped

volumes:
  mongodb-data:
    driver: local